export const apiRoutes = {
    signIn: 'auth/sign-in',
    signUp: 'auth/sign-up',
    signOut: 'auth/logout',
    location: 'location',
    trip: 'trip',
    tripSearch: 'trip/search',
    allBookings: 'booking',
    booking: 'booking',
    bookingPnr: 'booking/pnr',
    userBooking: 'booking/user/all',
    cancelBooking: 'booking/cancel',
    user: 'user',
    myBookings: 'booking/user/all',
    renewToken: 'auth/renew-token',
};
